services:
  #PostgreSQL
  db:
    image: postgres:15
    container_name: ticket_db
    environment:
      POSTGRES_DB: ticket_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 321654
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #Backend
  backend:
    build: ./backend
    container_name: ticket_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticket_system_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 321654

  #Frontend
  frontend:
    build: ./frontend
    container_name: ticket_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

volumes:
  postgres_data: